### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getLogger'

### ISSUE THREAD

**Issue by vinaybommana** [taspinar/twitterscraper#129]
Hi,
I am running the twitterscraper program on fedora 28,

I am getting the following error when I run the program

```
Traceback (most recent call last):
  File "/usr/bin/twitterscraper", line 11, in <module>
    load_entry_point('twitterscraper==0.7.1', 'console_scripts', 'twitterscraper')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/twitterscraper/__init__.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/twitterscraper/query.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/twitterscraper/logging.py", line 4, in <module>
AttributeError: 'module' object has no attribute 'getLogger'

```

I've searched for the issue, it seems that twitterscraper's logging.py and python logging.py are conflicting. Any insights about this ?

Thank you

**Comment by lapp0** [comment]
This is an issue with `0.7.1` in python2. You can either run it using python3, or you can revert to `0.7.0`

**Comment by vinaybommana** [comment]
Thank you that solved it.

```
python3 setup.py install
```

**Comment by jjanjj** [comment]
I have the same issue with the error AttributeError: 'module' object has no attribute 'getLogger'.
But my Python version is 3.6.5. So is this fine or should I still run "phyton3 setup.py install"? If yes, where? In cmd or in phyton project? When I try in phyton project I get an syntax error. In cmd as well (the command "python3" is either misspelled or could not be found)

I am a beginner and will appriciate your help! I need to take advantage of twitterscrapper for my master thesis. 

Thanks a lot!
