### ISSUE TITLE
Failed to parse JSON

### ISSUE THREAD

**Issue by isaacimholt** [taspinar/twitterscraper#137]
ERROR: Failed to parse JSON "Expecting value: line 1 column 1 (char 0)" while requesting "https://twi
tter.com/i/search/timeline?f=tweets&vertical=default&include_available_features=1&include_entities=1&
reset_error_state=false&src=typd&max_position=TWEET-425002525969121280-427502182905434112&q=%23fracro
%20since%3A2013-08-11%20until%3A2014-03-24&l=None"
Traceback (most recent call last):
  File "c:\users\gopro~1\docume~1\proget~2\sms-us~1\venv\lib\site-packages\twitterscraper\query.py",
 line 53, in query_single_page
    json_resp = json.loads(response.text)
  File "C:\Users\gopro_015\AppData\Local\Programs\Python\Python36\Lib\json\__init__.py", line 354
, in loads
    return _default_decoder.decode(s)
  File "C:\Users\gopro_015\AppData\Local\Programs\Python\Python36\Lib\json\decoder.py", line 339,
 in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\gopro_015\AppData\Local\Programs\Python\Python36\Lib\json\decoder.py", line 357,
 in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by isaacimholt** [comment]
Operating System
			Windows 10 Pro 64-bit
		CPU
			Intel Core i5 7200U @ 2.50GHz	55 °C
			Kaby Lake-U/Y 14nm Technology
		RAM
			8,00GB Single-Channel Unknown @ 1064MHz (15-15-15-35)
		Motherboard
			Dell Inc. 0M4RDT (U3E1)
		Graphics
			Generic PnP Monitor (1920x1080@60Hz)
			S24D330 (1920x1080@59Hz)
			Intel HD Graphics 620 (Dell)
		Storage
			238GB SanDisk X400 2.5 7MM 256GB (SATA (SSD))	34 °C
		Optical Drives
			No optical disk drives detected
		Audio
			Realtek Audio

Python 3.6

**Comment by lapp0** [comment]
Can you please try `0.8.0`? I believe I have removed the headers which caused the `JSONDecodeError`

**Comment by isaacimholt** [comment]
I've updated but it's not clear yet if the bug is fixed due to #138

**Comment by isaacimholt** [comment]
It appears it's working now, I'm not getting any errors
