### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by isaacimholt** [taspinar/twitterscraper#138]
Traceback (most recent call last):
	  File "C:\Users\Gopro_015\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "C:\Users\Gopro_015\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "C:\Users\GOPROJ~1\DOCUME~1\PROGET~2\SMS-US~1\venv\Scripts\twitterscraper.exe\__main__.py", line 9, in <module>
	  File "c:\users\goproj~1\docume~1\proget~2\sms-us~1\venv\lib\site-packages\twitterscraper\main.py", line 106, in main
		x.text, x.html])
	  File "c:\users\goproj~1\docume~1\proget~2\sms-us~1\venv\lib\encodings\cp1252.py", line 19, in encode
		return codecs.charmap_encode(input,self.errors,encoding_table)[0]
	UnicodeEncodeError: 'charmap' codec can't encode characters in position 13-14: character maps to <undefined>

I am using the query_tweets_once_generator function with version 0.8 of twitterscraper on python 3.6 Win10 64 

seems to be a problem with the csv writer in python, my own code had the same error, I will see what I can find

**Comment by isaacimholt** [comment]
change the csv file open to specify the encoding:
`with open(file_name, 'w', newline='', encoding='utf-8') as csv_file:`
this resolves my issue

**Comment by lapp0** [comment]
Could you make a PR?
