### ISSUE TITLE
No tweets being scraped and getting AttributeError and UnicodeEncode Error

### ISSUE THREAD

**Issue by Anmolr7** [taspinar/twitterscraper#162]
twitterscraper Trump --limit 500 -c -o tweets.csv
INFO: queries: ['Trump since:2006-03-21 until:2006-11-08', 'Trump since:2006-11-08 until:2007-06-28', 'Trump since:2007-06-28 until:2008-02-15', 'Trump since:2008-02-15 until:2008-10-04', 'Trump since:2008-10-04 until:2009-05-25', 'Trump since:2009-05-25 until:2010-01-12', 'Trump since:2010-01-12 until:2010-09-01', 'Trump since:2010-09-01 until:2011-04-21', 'Trump since:2011-04-21 until:2011-12-09', 'Trump since:2011-12-09 until:2012-07-29', 'Trump since:2012-07-29 until:2013-03-18', 'Trump since:2013-03-18 until:2013-11-05', 'Trump since:2013-11-05 until:2014-06-25', 'Trump since:2014-06-25 until:2015-02-12', 'Trump since:2015-02-12 until:2015-10-03', 'Trump since:2015-10-03 until:2016-05-22', 'Trump since:2016-05-22 until:2017-01-09', 'Trump since:2017-01-09 until:2017-08-29', 'Trump since:2017-08-29 until:2018-04-18', 'Trump since:2018-04-18 until:2018-12-07']
INFO: Querying Trump since:2006-03-21 until:2006-11-08
INFO: Querying Trump since:2006-11-08 until:2007-06-28
INFO: Querying Trump since:2007-06-28 until:2008-02-15
INFO: Querying Trump since:2008-02-15 until:2008-10-04
INFO: Querying Trump since:2008-10-04 until:2009-05-25
INFO: Querying Trump since:2009-05-25 until:2010-01-12
INFO: Querying Trump since:2010-01-12 until:2010-09-01
INFO: Querying Trump since:2010-09-01 until:2011-04-21
INFO: Querying Trump since:2011-04-21 until:2011-12-09
INFO: Querying Trump since:2011-12-09 until:2012-07-29
INFO: Querying Trump since:2012-07-29 until:2013-03-18
INFO: Querying Trump since:2013-03-18 until:2013-11-05
INFO: Querying Trump since:2013-11-05 until:2014-06-25
INFO: Querying Trump since:2014-06-25 until:2015-02-12
INFO: Querying Trump since:2015-02-12 until:2015-10-03
INFO: Querying Trump since:2015-10-03 until:2016-05-22
INFO: Querying Trump since:2016-05-22 until:2017-01-09
INFO: Querying Trump since:2017-01-09 until:2017-08-29
INFO: Querying Trump since:2017-08-29 until:2018-04-18
INFO: Querying Trump since:2018-04-18 until:2018-12-07
INFO: Got 0 tweets for Trump%20since%3A2015-10-03%20until%3A2016-05-22.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2013-03-18%20until%3A2013-11-05.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2010-01-12%20until%3A2010-09-01.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2008-10-04%20until%3A2009-05-25.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2009-05-25%20until%3A2010-01-12.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2007-06-28%20until%3A2008-02-15.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2016-05-22%20until%3A2017-01-09.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2014-06-25%20until%3A2015-02-12.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2012-07-29%20until%3A2013-03-18.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2017-01-09%20until%3A2017-08-29.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2006-03-21%20until%3A2006-11-08.
INFO: Got 0 tweets for Trump%20since%3A2008-02-15%20until%3A2008-10-04.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2010-09-01%20until%3A2011-04-21.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2011-12-09%20until%3A2012-07-29.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2017-08-29%20until%3A2018-04-18.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2011-04-21%20until%3A2011-12-09.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2015-02-12%20until%3A2015-10-03.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2013-11-05%20until%3A2014-06-25.
INFO: Got 0 tweets (0 new).
INFO: Got 0 tweets for Trump%20since%3A2006-11-08%20until%3A2007-06-28.
INFO: Got 0 tweets (0 new).
ERROR: An unknown error occurred! Returning tweets gathered so far.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/query.py", line 124, in query_tweets_once_generator
    pos is None
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/query.py", line 86, in query_single_page
    except json.decoder.JSONDecodeError as e:
AttributeError: 'module' object has no attribute 'JSONDecodeError'
INFO: Got 20 tweets for Trump%20since%3A2018-04-18%20until%3A2018-12-07.
INFO: Got 20 tweets (20 new).
Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 11, in <module>
    load_entry_point('twitterscraper==0.9.3', 'console_scripts', 'twitterscraper')()
  File "/usr/local/lib/python2.7/dist-packages/twitterscraper/main.py", line 112, in main
    x.text, x.html])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 131-132: ordinal not in range(128)

**Comment by pachocamacho1990** [comment]
Same here, don't know what's going on. Maybe the search page of twitter changed something ...

**Comment by taspinar** [comment]
@Anmolr7 Python 2.7 is not supported. Could you try again with Python 3?
