### ISSUE TITLE
SyntaxError: positional argument follows keyword argument

### ISSUE THREAD

**Issue by shpshp** [taspinar/twitterscraper#166]
```
>twitterscraper Trump --limit 100 --output=tweets.json
Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 11, in <module>
    load_entry_point('twitterscraper==0.9.3', 'console_scripts', 'twitterscraper')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/twitterscraper-0.9.3-py3.6.egg/twitterscraper/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/usr/local/lib/python3.6/dist-packages/twitterscraper-0.9.3-py3.6.egg/twitterscraper/query.py", line 222
SyntaxError: positional argument follows keyword argument
```

**Comment by tinyweasel** [comment]
The phrase you're searching should be a string, so "Trump" instead of Trump.
