### ISSUE TITLE
Invalid Syntax? 

### ISSUE THREAD

**Issue by nbreide** [taspinar/twitterscraper#174]
Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 9, in <module>
    load_entry_point('twitterscraper==0.9.3', 'console_scripts', 'twitterscraper')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.14-intel/egg/twitterscraper/__init__.py", line 13, in <module>
  File "/Library/Python/2.7/site-packages/twitterscraper-0.9.3-py2.7.egg/twitterscraper/query.py", line 291
    logger.info(f"Got user information from username {user}")
                                                           ^
SyntaxError: invalid syntax

**Comment by nikber84** [comment]
I have same error

**Comment by Kallirroi** [comment]
This is not fixed - had to edit it manually on `/Library/Python/2.7/site-packages/twitterscraper-0.9.3-py2.7.egg/twitterscraper/query.py`.
