### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by sils** [taspinar/twitterscraper#20]
while running `TwitterScraper "test" --output tweets.json --all` for ~10 minutes

```
ERROR: An unknown error occurred! Returning tweets gathered so far.
Traceback (most recent call last):
  File "/home/lasse/prog/tie/twitterscraper/twitterscraper/query.py", line 96, in query_tweets_once
    pos is None
  File "/home/lasse/prog/tie/twitterscraper/twitterscraper/query.py", line 46, in query_single_page
    tweets = list(Tweet.from_html(html))
  File "/home/lasse/prog/tie/twitterscraper/twitterscraper/tweet.py", line 34, in from_html
    yield cls.from_soup(tweet)
  File "/home/lasse/prog/tie/twitterscraper/twitterscraper/tweet.py", line 19, in from_soup
    user=tweet.find('span', 'username').text[1:],
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by sils** [comment]
@adtac can you fix this?
