### ISSUE TITLE
Error  while using the twitterscraper command

### ISSUE THREAD

**Issue by Pavan-Devara** [taspinar/twitterscraper#206]
Traceback (most recent call last):
  File "/home/pavan/.local/bin/twitterscraper", line 9, in <module>
    load_entry_point('twitterscraper==1.2.0', 'console_scripts', 'twitterscraper')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/twitterscraper/__init__.py", line 13, in <module>
  File "/home/pavan/.local/lib/python2.7/site-packages/twitterscraper-1.2.0-py2.7.egg/twitterscraper/query.py", line 306
    logger.info(f"Got user information from username {user}")
                                                           ^
SyntaxError: invalid syntax

**Comment by StormFalcon32** [comment]
Try downgrading to 1.1.0

**Comment by Camilo-Lesmes** [comment]
Actualmente la librería trabaja con Python3, prueba creando un entorno y prueba nuevamente

> sudo apt-get install python3-venv -y

**Comment by bdferris642** [comment]
I have had the same problem on both 1.2 and 1.1
Errors out on:
logger.info(f"Got user information from username {user}")
with a syntax error

**Comment by bdferris642** [comment]
I solved this problem by downgrading to 1.1 and creating a new virtualenv that uses python 3.6
f-strings (for example: f"Got user information from username {user}") are not a thing in python 3.5

**Comment by taspinar** [comment]
This issue should be fixed in version 1.3.1 where the two uses of f-strings have been replaced with string.format()
