### ISSUE TITLE
ImportError: No module named 'tweet'

### ISSUE THREAD

**Issue by sims1253** [taspinar/twitterscraper#21]
I get the following error when trying to use this. 
Installed in a venv via pip
```
Traceback (most recent call last):
  File "collector.py", line 1, in <module>
    import twitterscraper
  File "/home/m0hawk/Documents/dev/TUHH/testvenv/lib/python3.5/site-packages/twitterscraper/__init__.py", line 13, in <module>
    from twitterscraper.query import query_tweets
  File "/home/m0hawk/Documents/dev/TUHH/testvenv/lib/python3.5/site-packages/twitterscraper/query.py", line 14, in <module>
    from tweet import Tweet
ImportError: No module named 'tweet'
```

**Comment by sils** [comment]
via pip from source you mean?

**Comment by sils** [comment]
give us commands to reproduce a fresh venv with your exact installation method please, remember how I do those usually?

**Comment by sims1253** [comment]
```
virtualenv test
source test/bin/activate
pip install twitterscraper
```

**Comment by sils** [comment]
can you do from source please, `pip install .`

**Comment by sils** [comment]
or rather `python setup.py install` maybe something's wrong with the distribution

**Comment by sims1253** [comment]
from source it works.
clone repo

**Comment by sils** [comment]
use it from source, keep this open

**Comment by sils** [comment]
@taspinar I'm not sure which version is released on pypi but there's likely a distribution problem

**Comment by taspinar** [comment]
@sims1253 I have uploaded the latest version to PyPi, which includes PR #18 . Can you check if this can be installed correctly via pip install?

**Comment by sims1253** [comment]
Fresh venv yielded this:
```
[m0hawk@m0hawk-PC Downloads]$ virtualenv test
Using base prefix '/usr'
New python executable in /home/m0hawk/Downloads/test/bin/python
Installing setuptools, pip, wheel...done.
[m0hawk@m0hawk-PC Downloads]$ source test/bin/activate
(test) [m0hawk@m0hawk-PC Downloads]$ pip install twitterscraper
Collecting twitterscraper
  Downloading twitterscraper-0.2.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-onxz8q3i/twitterscraper/setup.py", line 6, in <module>
        with open('requirements.txt') as requirements:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-onxz8q3i/twitterscraper/
(test) [m0hawk@m0hawk-PC Downloads]$ pip --version
pip 9.0.1 from /home/m0hawk/Downloads/test/lib/python3.5/site-packages (python 3.5)
(test) [m0hawk@m0hawk-PC Downloads]$ which pip
/home/m0hawk/Downloads/test/bin/pip

```

**Comment by taspinar** [comment]
In the latest version (0.2.6) requirements.txt is included in the package with MANIFEST.in.
Could you check if this fixes the problem?

**Comment by sims1253** [comment]
works for me

**Comment by sils** [comment]
@sims1253 then close it?
