### ISSUE TITLE
Error INFO USER-AGENT

### ISSUE THREAD

**Issue by TrungKien1230** [taspinar/twitterscraper#236]
Hello @taspinar, I have this problem when I tried to get tweets from twitterscraper:

INFO: {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13'}
Traceback (most recent call last):
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 456, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert access denied')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 462, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert access denied')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert access denied')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/nguy/PycharmProjects/Streaming_Tweets_Data/twitterScraper.py", line 5, in <module>
    from twitterscraper import query_tweets
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\twitterscraper\__init__.py", line 13, in <module>
    from twitterscraper.query import query_tweets
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\twitterscraper\query.py", line 72, in <module>
    proxies = get_proxies()
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\twitterscraper\query.py", line 42, in get_proxies
    response = requests.get(PROXY_URL)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\nguy\AppData\Local\Continuum\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='free-proxy-list.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert access denied')])")))

**Comment by Makoto1021** [comment]
Hi @TrungKien1230 , have you solved this issue? I"m having the same problem. I first thought it was due to trying to scrape too many tweets at one go. So I waited for few days and tried again, but this error is still persistent. It'd be nice if you could share the solution for this! thanks

**Comment by avanibhatnagar** [comment]
@Makoto1021 @TrungKien1230  Have you been able to find a way to solve this? It was working last week no problem, but I get the same error now

**Comment by JoeCarlPSU** [comment]
same issues here

**Comment by TrungKien1230** [comment]
As you can read on Policy of Twitter API. You have 2 ways to retrieve tweets: track in the pass (7 days) and streaming (right now) and you cannot retrieve over amount of tweets in a unit of time. With the streaming you can take as much as you want. This problem is because you took too much already. 

Give me your email, I will send you my code with restAPI (take tweets in the pass)
