### ISSUE TITLE
lxml twitterscraper

### ISSUE THREAD

**Issue by muhjaury** [taspinar/twitterscraper#249]
> INFO: {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13'}
> Traceback (most recent call last):
>   File "/home/mist/.local/bin/twitterscraper", line 5, in <module>
>     from twitterscraper.main import main
>   File "/home/mist/.local/lib/python3.7/site-packages/twitterscraper/__init__.py", line 13, in <module>
>     from twitterscraper.query import query_tweets
>   File "/home/mist/.local/lib/python3.7/site-packages/twitterscraper/query.py", line 73, in <module>
>     proxies = get_proxies()
>   File "/home/mist/.local/lib/python3.7/site-packages/twitterscraper/query.py", line 44, in get_proxies
>     soup = BeautifulSoup(response.text, 'lxml')
>   File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 156, in __init__
>     % ",".join(features))
> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

When I use 

> pip install lxml

Result is 

> Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (3.5.0)

Found that problem, what should I do? Thankyou

**Comment by NicholasDow** [comment]
I am also having this specific issue

**Comment by lapp0** [comment]
@NicholasDow you may have multiple conflicting python installations. I recommend

1) trying this fix https://stackoverflow.com/a/52259845

2) trying to create a virtualenv and install twitterscraper in there
