### ISSUE TITLE
Thread 'Supervisor' crashed: AttributeError("'IMapUnorderedIterator' object has no attribute '_write_to'")

### ISSUE THREAD

**Issue by bluebug565** [taspinar/twitterscraper#286]
Thread 'Supervisor' crashed: AttributeError("'IMapUnorderedIterator' object has no attribute '_write_to'")
Traceback (most recent call last):
  File "C:\Users\Oluwaseyi\Anaconda3\lib\site-packages\billiard\pool.py", line 504, in run
    return self.body()
  File "C:\Users\Oluwaseyi\Anaconda3\lib\site-packages\billiard\pool.py", line 563, in body
    pool._maintain_pool()
  File "C:\Users\Oluwaseyi\Anaconda3\lib\site-packages\billiard\pool.py", line 1342, in _maintain_pool
    joined = self._join_exited_workers()
  File "C:\Users\Oluwaseyi\Anaconda3\lib\site-packages\billiard\pool.py", line 1234, in _join_exited_workers
    write_to = job._write_to
AttributeError: 'IMapUnorderedIterator' object has no attribute '_write_to'

**Comment by lapp0** [comment]
Please share your command so I can attempt to reproduce.

**Comment by sivaji1233** [comment]
I do have same issue. I just tried basic "twitterscraper Trump --limit 1000 --output=tweets.json" and also different queries using python as well.

**Comment by sivaji1233** [comment]
@bluebug565 was you able to resolve the issue?

**Comment by saeideh676** [comment]
I have this issue too. can anyone help?
