### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by wongpenghong** [taspinar/twitterscraper#295]
when i run on version `twitterscraper==1.4.0` , popup some error

**Comment by lapp0** [comment]
Please post your full traceback and command.

**Comment by javad94** [comment]
I have this issue too.
traceback:
```python
INFO: {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13'}
Traceback (most recent call last):
  File "/share/python_scripts/twitterbotsearch.py", line 1, in <module>
    from twitterscraper import query_tweets
  File "/home/pi/.local/lib/python3.6/site-packages/twitterscraper/__init__.py", line 13, in <module>
    from twitterscraper.query import query_tweets
  File "/home/pi/.local/lib/python3.6/site-packages/twitterscraper/query.py", line 73, in <module>
    proxies = get_proxies()
  File "/home/pi/.local/lib/python3.6/site-packages/twitterscraper/query.py", line 46, in get_proxies
    list_tr = table.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by zhicheng0501** [comment]
> I have this issue too.
> traceback:
> 
> ```python
> INFO: {'User-Agent': 'Mozilla/5.0 (Windows; U; Windows NT 6.1; x64; fr; rv:1.9.2.13) Gecko/20101203 Firebird/3.6.13'}
> Traceback (most recent call last):
>   File "/share/python_scripts/twitterbotsearch.py", line 1, in <module>
>     from twitterscraper import query_tweets
>   File "/home/pi/.local/lib/python3.6/site-packages/twitterscraper/__init__.py", line 13, in <module>
>     from twitterscraper.query import query_tweets
>   File "/home/pi/.local/lib/python3.6/site-packages/twitterscraper/query.py", line 73, in <module>
>     proxies = get_proxies()
>   File "/home/pi/.local/lib/python3.6/site-packages/twitterscraper/query.py", line 46, in get_proxies
>     list_tr = table.find_all('tr')
> AttributeError: 'NoneType' object has no attribute 'find_all'
> ```

It is very likely to be caused by the empty list scraped from the proxy website.when the problem occurs, table should be empty. In this case, find_all method is not able to get anything from table.
you could wait for a moment and retry it. It should be back to normal very soon.

**Comment by lapp0** [comment]
What command are you running to get this traceback?

**Comment by javad94** [comment]
> What command are you running to get this traceback?

`torsocks twitterscraper Trump -l 1000`

**Comment by qreodium** [comment]
In query.py need change `table = soup.find('table',id='proxylisttable')` to `table = soup.find('table', {"class": 'table'})` because they change proxy site

**Comment by seaona** [comment]
Hi! I've changed the query.py as mentioned above, but I still don't succeed on solving the error. Any thoughts?
My query was just running the example script:

`examples/get_twitter_user_data.py`

![image](https://user-images.githubusercontent.com/54408225/132834172-60055507-fec7-45c7-950b-a5049fdd02b7.png)
