### ISSUE TITLE
AttributeError: 'IMapUnorderedIterator' object has no attribute '_write_to'

### ISSUE THREAD

**Issue by ahcisneros** [taspinar/twitterscraper#326]
INFO: queries: ['tesla since:2019-03-02 until:2019-03-03']
INFO: {'User-Agent': 'Opera/9.80 (X11; Linux i686; Ubuntu/14.10) Presto/2.12.388 Version/12.16', 'X-Requested-With': 'XMLHttpRequest'}
Thread 'Supervisor' crashed: AttributeError("'IMapUnorderedIterator' object has no attribute '_write_to'")
Traceback (most recent call last):
  File "C:\Users\Alexis\anaconda3\envs\tensorflow\lib\site-packages\billiard\pool.py", line 504, in run
    return self.body()
  File "C:\Users\Alexis\anaconda3\envs\tensorflow\lib\site-packages\billiard\pool.py", line 563, in body
    pool._maintain_pool()
  File "C:\Users\Alexis\anaconda3\envs\tensorflow\lib\site-packages\billiard\pool.py", line 1342, in _maintain_pool
    joined = self._join_exited_workers()
  File "C:\Users\Alexis\anaconda3\envs\tensorflow\lib\site-packages\billiard\pool.py", line 1234, in _join_exited_workers
    write_to = job._write_to
AttributeError: 'IMapUnorderedIterator' object has no attribute '_write_to'

**Comment by rorofaqod** [comment]
hello, I have a similar problem here

AttributeError: 'IMapUnorderedIterator' object has no attribute '_write_to'

did you found the solution yet?

**Comment by raulgal02** [comment]
have the same problem, had a solution?

**Comment by rorofaqod** [comment]
I don't. I end up using selenium

**Comment by raulgal02** [comment]
Me too,   Selenium far better,  thanks
