### ISSUE TITLE
Problem parsing proxy list

### ISSUE THREAD

**Issue by crowley285** [taspinar/twitterscraper#363]
the proxy source https://free-proxy-list.net/ probably changed things around it's proxy table which is no longer under the id "proxylisttable" and so the line 48 in query.py returns None.

Traceback (most recent call last):
File "D:/tasks/TwitterFeed.py", line 9, in <module>
   from twitterscraper import query_tweets
File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\twitterscraper\__init__.py", line 13, in <module>
   from twitterscraper.query import query_tweets
File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\twitterscraper\query.py", line 76, in <module>
   proxies = get_proxies()
File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\twitterscraper\query.py", line 49, in get_proxies
   list_tr = table.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by mahdishemshadi** [comment]
Hi
It still does not work and gives the same error, but in different place

C:\Users\Mehdi\.virtualenvs\MRI-oQo_kXvf\Scripts\python.exe "F:/workspace/Finnogate/twitter scraper/examples/get_twitter_user_data.py"
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "F:\workspace\Finnogate\twitter scraper\examples\get_twitter_user_data.py", line 20, in get_user_info
    twitter_user_data["user"] = user_info.user
AttributeError: 'NoneType' object has no attribute 'user'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\workspace\Finnogate\twitter scraper\examples\get_twitter_user_data.py", line 54, in <module>
    main()
  File "F:\workspace\Finnogate\twitter scraper\examples\get_twitter_user_data.py", line 41, in main
    for user in pool.map(get_user_info,users):
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'user'

Process finished with exit code 1

**Comment by mahdishemshadi** [comment]
Hi
It still does not work and gives the same error in another place


C:\Users\Mehdi\.virtualenvs\MRI-oQo_kXvf\Scripts\python.exe "MYDIR/twitter scraper/examples/get_twitter_user_data.py"
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "MYDIR\twitter scraper\examples\get_twitter_user_data.py", line 20, in get_user_info
    twitter_user_data["user"] = user_info.user
AttributeError: 'NoneType' object has no attribute 'user'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "MYDIR\twitter scraper\examples\get_twitter_user_data.py", line 54, in <module>
    main()
  File "MYDIR\twitter scraper\examples\get_twitter_user_data.py", line 41, in main
    for user in pool.map(get_user_info,users):
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "c:\program files\python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'user'

Process finished with exit code 1

**Comment by burakugurr** [comment]
I also get this error. What's the solution to the problem?

**Comment by neogeos** [comment]
hi i got this error     list_tr = table.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by AdrienMau** [comment]
Same error.
