### ISSUE TITLE
FakeUserAgentError: Error occurred during getting browser

### ISSUE THREAD

**Issue by 3ruce** [taspinar/twitterscraper#54]
Running twitterscraper, I ran into this error using the example given in the readme `twitterscraper Trump%20since%3A2017-01-03%20until%3A2017-01-04 -o tweets.json`

I was running a version from March and then upgraded to the latest master.zip but I still got the same error... Any ideas on how to resolve this? I'm running Ubuntu 16.04...

```
Traceback (most recent call last):
  File "/usr/local/bin/twitterscraper", line 9, in <module>
    load_entry_point('twitterscraper==0.3.1', 'console_scripts', 'twitterscraper')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/twitterscraper/__init__.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/twitterscraper/query.py", line 14, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fake_useragent/fake.py", line 139, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
fake_useragent.errors.FakeUserAgentError: Error occurred during getting browser

```

**Comment by 3ruce** [comment]
Ok, so this seemed to fix the problem...

`sudo pip install twitterscraper --upgrade`
