### ISSUE TITLE
weird limit behavior

### ISSUE THREAD

**Issue by dkennedy778** [taspinar/twitterscraper#84]
[check out this parse using -l as the delimiter](https://gyazo.com/2cdad9f972631da661d090c3bb8b5077)

[Now the exact same parse using --limit](https://gyazo.com/cf199c7ac788ec517bdbd42cfa94124e)

Totally different behavior! Looking over your main code it seems these two calls are functionally the same.

A few other weird instances

[Exiting after hitting an undefined critical error, I've seen this on several parses](https://gyazo.com/ed761ace9c169b097be8ec237c1f7580)
 
[Exact same parse finding different numbers of tweets, all exiting before the limit](https://gyazo.com/bae08f0f978b8c85e508b39039972e59)

[Exiting for no specified reason, see first attempt for another example of the undefined error](https://gyazo.com/9d58659c5bd454f12a3ddc861529d92c)

None of the parses that return significant numbers of results are giving me frequent INFO updates.

**Comment by taspinar** [comment]
You are raising some interesting concerns. I hope I'll have some time in the coming weeks to address these issues.

**Comment by dkennedy778** [comment]
Cool, thanks taspinar. I'll update this issue log if I find anything else weird

**Comment by Plightt** [comment]
I'm troubleshooting the same issue. Scraping "Litecoin" will yield some (say 60k results between Jan '12 to Dec '13), but will error out with this same issue for other date periods/limits. The limit # appears to be a factor, but I'm new to Python and it's hard to pinpoint the source of this one.

This works:

query_tweets(query="Litecoin", limit=5000, begindate=datetime.date(2014, 1, 1),enddate=datetime.date(2014, 6, 1))

but this doesn't:

query_tweets(query="Litecoin", limit=10000, begindate=datetime.date(2014, 1, 1),enddate=datetime.date(2014, 6, 1))

Error is below. I've just installed the package. I tried an earlier version (before lang support was introduced), however, encountered the same issue - so perhaps a change to twitter search?

Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\twitterscraper\query.py", line 92, in query_tweets_once
    pos is None
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\twitterscraper\query.py", line 37, in query_single_page
    json_resp = response.json()
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dkennedy778** [comment]
Hey plight, was the older version you tried out before the December 19th commits? The changes to bd,ed, and parallelization are the only potentially confounding factors I'm seeing here

**Comment by taspinar** [comment]
@Plightt It is not exactly clear to me what causes the JSONDecoderError, but with the latest version JSONDecoderError's are catched properly and the process continues scraping. 

@dkennedy778 Since the pictures you attached can not be viewed anymore, I dont really know what the problem is / was. 
Can you check if the problem still persists with the latest version? (0.5.0)

**Comment by dkennedy778** [comment]
@taspinar Hey taspinar, not sure what's up with those links. Everything displays fine for me, sorry about that. I went ahead and updated the hyperlinks with images hosted through github, let me know if it works 

I'll be out of town for a few days, but I'll be sure to try out 0.5.0 when I get back, thanks!

**Comment by rreid12** [comment]
I have only started using twitterscraper in the past few weeks, but I believe I am seeing similar issues to @dkennedy778 and @Plightt.

```twitterscraper Trump -l 1000 -bd 2017-01-01 -ed 2017-06-01 -o tweets.json``` 
Results in 116 total tweets.

```twitterscraper Trump -l 10000 -bd 2017-01-01 -ed 2017-06-01 -o tweets.json```
Results in 446 total tweets.

```twitterscraper Trump -l 40000 -bd 2017-01-01 -ed 2017-06-01 -o tweets.json```
Results in 2047 total tweets.

Then when removing -bd and -ed flags:

```twitterscraper Trump -l 1000 -o tweets.json```
Results in 278 total tweets.

```twitterscraper Trump -l 10000 -o tweets.json```
Results in 1203 total tweets.

```twitterscraper Trump -l 40000 -o tweets.json```
Results in 1303 total tweets.

There doesn't seem to be much consistency in how many tweets are discovered, so it's even more difficult for me to speculate what could be causing the issue. 

If anyone has found the root cause of this issue and managed to fix it, please let me know!

Also, if anyone would like more information from me like screenshots, more examples, etc. I would be happy to provide it.

**Comment by taspinar** [comment]
@rreid12 
I noticed the results are consistent (not sure if this is the case on every platform/OS) if you set the number of processes to 1, could you try to run the query with the command line argument `-p 1`  ?

**Comment by KolosDan** [comment]
@taspinar -p 1 usually gives out no tweets at all

**Comment by taspinar** [comment]
@KolosDan I noticed that this is caused by the way the number of days is divided over the number of pooling processes. With version 0.7.0 "-p 1" should also give output data.

**Comment by dkennedy778** [comment]
@taspinar Hey Taspinar, thanks for keeping up to date with this. When I get a chance I'll rerun my tests and let you know how it goes
